# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
