# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 22:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('concesionarioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('datid', models.AutoField(primary_key=True, serialize=False)),
                ('datnombre', models.CharField(max_length=50)),
                ('datapellido', models.CharField(blank=True, max_length=50, null=True)),
                ('datipoid', models.CharField(blank=True, max_length=20, null=True)),
                ('datnumeroid', models.CharField(blank=True, max_length=20, null=True)),
                ('datelefono', models.CharField(blank=True, max_length=20, null=True)),
                ('datcorreo', models.CharField(blank=True, max_length=50, null=True)),
                ('usuid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rolid', models.AutoField(primary_key=True, serialize=False)),
                ('roltipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionarioapp.Rol')),
                ('usuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('vehplaca', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vehmodelo', models.IntegerField()),
                ('vehmarca', models.CharField(max_length=50)),
                ('vehestado', models.CharField(blank=True, max_length=30, null=True)),
                ('vehprecio', models.IntegerField()),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionarioapp.Categoria')),
                ('datid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionarioapp.DatosPersonales')),
            ],
        ),
    ]
