# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-23 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionarioapp', '0003_auto_20171110_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='vehfoto',
            field=models.ImageField(default='vehiculos/vehiculo.png', upload_to='vehiculos'),
        ),
    ]
