# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-05 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionarioapp', '0004_vehiculo_vehfoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='datospersonales',
            name='foto',
            field=models.ImageField(default=b'usuarios/usuario.png', upload_to=b'usuarios'),
        ),
    ]
