# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-05 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionarioapp', '0005_datospersonales_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='datipoid',
            field=models.CharField(blank=True, choices=[(b'CC', 'C\xe9dula de Ciudadan\xeda (CC)'), (b'TI', 'Tarjeta de Identidad (TI)'), (b'RC', 'Registro Civil (RC)'), (b'CE', 'C\xe9dula de Extranjer\xeda (CE)'), (b'CI', 'Carn\xe9 de Identidad (CI)'), (b'DNI', 'Documento Nacional de Identidad (DNI)'), (b'DUI', 'Documento \xdanico de Identidad (DUI)')], default=b'CC', max_length=20, null=True),
        ),
    ]
